name: batwind
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - slugify
  - pip
  - git
  - pip:
    - pytest-console-scripts
    - batread
    
  #
  # These packages are used for testing
  #
  - pytest
  - pytest-cov
    
  #
  # This package is used for Codacy integration
  #
  - codacy-coverage
  
