name: batwind
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - matplotlib
  - slugify
  - colorlog
  - pip
  - git
  - pip:
    - pytest-console-scripts
    - batread>=1.1.0
    - griblet>=0.3.0
    - batcamp>=0.3.1
    
  #
  # These packages are used for testing
  #
  - pytest
  - pytest-cov
  - flake8
  - pooch
    
  #
  # This package is used for Codacy integration
  #
  - codacy-coverage
  
