name: starwinds-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - pip
  - pytest
  - pytest-cov
  - git
  - pip:
      - pytest-console-scripts
      - git+https://github.com/svaberg/starwinds-readplt.git
